---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# AKE_master

<!-- badges: start -->
<!-- badges: end -->

The goal of AKE_master is to contain all the essential code and documents for a thesis


## Essential directories

* data: R binary files (not on github)
* data-csv: Tidy data (not on github)
* data-raw: External data in various format, most often messy (not on github)
* docs: Background documents (not on github)
* R: Functions only (on github)
* R-scripts: Various preparatory scripts, not functions (on github)
  * **survey-response-only.R**: Scripts that reads in the excel "raw"-sheet (sheet 1) and only retains the first 166 columns (the actual survey response) and currently any column that ends with "footprint". In addition some additional (three) columns are currently also retrained. The furture plan is that the footprint variables will be calculated internally within R.
  * **survey_response-tidy.R**: Various initial wrangling (tidying and transformations).
* rmd: Thesis documents (on github)


## News

#### 2022-12-08

Seed the github repo


